# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
   include:
     - main
 paths:
   include:
     - MyTestAPI/*
     - azure-pipelines-test-api.yml
    
pool:
  vmImage: 'windows-NT'
  name: 'Inayat Custom Agents Pool'

variables:
  solution: MyTestAPI/**/*.csproj
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build_test_API
  jobs:
    - job: Build_API
      displayName: "Build the code of API"
      steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - script:
         echo this is the staging directory $(Build.ArtifactStagingDirectory)
        
      - task: VSTest@2
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          
          
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'TestAPIArtifact'

- stage: Deploy
  variables:
    environment: MyTestingEnvironment
  jobs:
    - deployment: Deploy
      environment: $(environment)
      strategy:
        runOnce:
          deploy:
            steps:
              - task: IISWebAppDeploymentOnMachineGroup@0
                inputs:
                  WebSiteName: 'MyTestAPI'
                  Package: '$(Agent.BuildDirectory)\**\*.zip'
         